export const LANGUAGES = [
  "en",
  "ko",
  "ar",
  "de",
  "es",
  "fr",
  "id",
  "it",
  "ja",
  "ms",
  "pt",
  "th",
  "tl",
  "tr",
  "vi",
] as const;

export const COUNTRY_CODES = [
  "US",
  "KR",
  "AE",
  "AU",
  "BR",
  "CA",
  "DE",
  "EG",
  "ES",
  "FR",
  "GB",
  "ID",
  "IL",
  "IT",
  "JP",
  "MY",
  "PH",
  "RU",
  "SA",
  "SG",
  "TH",
  "TR",
  "TW",
  "VN",
] as const;

export const CONTENT_LABELS = [
  "beauty",
  "fitness",
  "gaming",
  "fashion",
  "food",
  "travel",
  "tech",
  "music",
  "sports",
  "education",
  "lifestyle",
  "comedy",
  "art",
  "business",
  "health",
] as const;

export const FOLLOWER_GENDER_RATIOS = [
  "FEMALE_50",
  "FEMALE_60",
  "FEMALE_70",
  "MALE_50",
  "MALE_60",
  "MALE_70",
] as const;

export const FOLLOWER_AGES = [
  "18-24",
  "25-34",
  "35-44",
  "45-54",
  "55+",
] as const;

export const GENDER_RATIO_LABELS: Record<
  (typeof FOLLOWER_GENDER_RATIOS)[number],
  string
> = {
  FEMALE_50: "50%+ Female",
  FEMALE_60: "60%+ Female",
  FEMALE_70: "70%+ Female",
  MALE_50: "50%+ Male",
  MALE_60: "60%+ Male",
  MALE_70: "70%+ Male",
};

export const LANGUAGE_LABELS: Record<(typeof LANGUAGES)[number], string> = {
  ar: "Arabic",
  de: "German",
  en: "English",
  es: "Spanish",
  fr: "French",
  id: "Indonesian",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  ms: "Malay",
  pt: "Portuguese",
  th: "Thai",
  tl: "Filipino",
  tr: "Turkish",
  vi: "Vietnamese",
};

export const COUNTRY_LABELS: Record<(typeof COUNTRY_CODES)[number], string> = {
  US: "United States",
  KR: "South Korea",
  AE: "UAE",
  AU: "Australia",
  BR: "Brazil",
  CA: "Canada",
  DE: "Germany",
  EG: "Egypt",
  ES: "Spain",
  FR: "France",
  GB: "United Kingdom",
  ID: "Indonesia",
  IL: "Israel",
  IT: "Italy",
  JP: "Japan",
  MY: "Malaysia",
  PH: "Philippines",
  RU: "Russia",
  SA: "Saudi Arabia",
  SG: "Singapore",
  TH: "Thailand",
  TR: "Turkey",
  TW: "Taiwan",
  VN: "Vietnam",
};
